### ISSUE TITLE
Unable to load API

### ISSUE THREAD

**Issue by OliMations** [DolphDev/pynationstates#6]
So I installed the nationstates module using pip, `pip install nationstates`
But when i try to import the nationstates api. It says "cannot import Api"
I know this works as on another system where I installed the package a few months ago, it imported fine.
Just on this new system where I installed nationstates just yesterday it gives me that error

Thanks!

**Comment by DolphDev** [comment]
Could you post the full traceback/error message?

Thanks for reporting
